# -*- coding: utf-8 -*-
"""
THE GOLDEN PAYLOADS - the JSON contract a second client is built on, pinned.

Slice 15 adds a React UI that renders from `fixtures/api/` with no Python process and no socket.
That makes these files a contract in both directions, and this module holds both ends:

    layer 1   they are a faithful, current copy of the API. A rebuild is byte-identical, the
              matrix is complete, and every run a history row names resolves to a file. A
              `render.py` change that alters the payload fails HERE, as a stale rebuild, rather
              than as a broken UI three weeks later.
    layer 2   the shape every component depends on. Above all trap 1: a run that concluded
              nothing still carries `counts`, and `coverage.concluded` is the only honest gate
              for the tile row. That is pinned so nobody "tidies" the payload into a shape the
              UI then gets subtly wrong - in either direction.

Like `fixtures/demopms/`, these files are generated by a tool and never edited by hand.
"""
import json
import pathlib

import pytest

from hotelcontrols.kernel import Outcome
from hotelcontrols.providers.registry import names as provider_names
from hotelcontrols.spec import available, available_tenants
from hotelcontrols.web import App
from tools import dump_api_fixtures

GOLDEN = dump_api_fixtures.TARGET_DIR
OUTCOMES = {outcome.value for outcome in Outcome}


def golden(name: str):
    return json.loads((GOLDEN / name).read_text(encoding="utf-8"))


def matrix():
    app = App()
    for control_id in available():
        for tenant_id in available_tenants():
            for capture in app.captures_for(tenant_id):
                yield control_id, tenant_id, capture


RUNS = ["run/%s.%s.%s.json" % cell for cell in matrix()]


# ---------------------------------------------------------------------------------------
class TestLayer1TheGoldensAreTheApi:

    def test_a_rebuild_is_byte_identical(self):
        """Generated, never edited - the fixtures/demopms rule applied to the API's output.
        If this fails after a deliberate payload change: `python3 -m tools.dump_api_fixtures`,
        then read the diff, because the diff IS the contract change."""
        built = dump_api_fixtures.build()
        on_disk = {p.relative_to(GOLDEN).as_posix(): p.read_text(encoding="utf-8")
                   for p in GOLDEN.rglob("*.json")}
        assert sorted(on_disk) == sorted(built), "files added or missing - rebuild"
        stale = [name for name in built if built[name] != on_disk[name]]
        assert not stale, "stale golden payloads: %s" % ", ".join(stale[:10])

    def test_the_check_command_agrees(self):
        assert dump_api_fixtures.main(["--check"]) == 0

    def test_the_full_matrix_is_present(self):
        """Every control x every property x every capture. A UI tested on three hand-picked
        runs is a UI tested on three runs; the states that break a page are the rare ones."""
        assert len(RUNS) == len(available()) * sum(
            len(App().captures_for(t)) for t in available_tenants())
        for name in RUNS:
            assert (GOLDEN / name).is_file(), name

    def test_every_run_a_history_names_resolves_to_a_stored_payload(self):
        """R1's promise, kept by the fixtures too: a past run is re-read, never re-run."""
        for control_id in available():
            for row in golden("history/%s.json" % control_id)["runs"]:
                assert (GOLDEN / "runs" / ("%s.json" % row["run_id"])).is_file(), row

    def test_a_stored_run_says_what_the_live_run_said(self):
        """`/api/runs/<id>` is what the React history page links to. It must carry the same
        verdicts and evidence as the run it stores - only the spec-derived extras (readiness,
        execution plan) are not re-derived for a past run."""
        for name in RUNS:
            live = golden(name)
            stored = golden("runs/%s.json" % live["run_id"])
            for key in ("control_id", "tenant_id", "provider", "evidence", "as_of", "blocked",
                        "coverage", "verdicts"):
                assert stored[key] == live[key], (name, key)
            assert stored.get("counts") == live.get("counts"), name


# ---------------------------------------------------------------------------------------
class TestLayer2TheShapeEveryComponentDependsOn:

    def test_trap_1_a_run_that_concluded_nothing_still_carries_counts(self):
        """THE trap. `ooo_room_protection` excludes all 28 rooms and concluded nothing - but
        `counts` is present, four numbers with a zero under FAIL. A component that renders
        tiles whenever `counts` exists reproduces finding F5 in a new language. Pinned so the
        UI's gate stays `coverage.concluded`, and so nobody removes `counts` from here thinking
        it a tidy-up: the history page charts it, correctly gated."""
        payload = golden("run/ooo_room_protection.sandbox.sandbox2026.json")
        assert payload["blocked"] is None
        assert payload["coverage"]["concluded"] is False
        assert payload["counts"] == {"PASS": 0, "FAIL": 0, "UNKNOWN": 0, "EXCLUDED": 28,
                                     "total": 28}
        assert "reached no conclusion" in payload["coverage"]["headline"]

    def test_a_blocked_run_carries_no_counts_at_all(self):
        """Criterion 8: the other no-tiles state, and the one that does omit the key."""
        payload = golden("run/resource_occupancy_consistency.sandbox.sandbox2026.json")
        assert payload["blocked"]
        assert "counts" not in payload
        assert payload["coverage"]["concluded"] is False

    @pytest.mark.parametrize("name", RUNS)
    def test_counts_are_present_exactly_when_the_run_was_not_blocked(self, name):
        payload = golden(name)
        assert ("counts" in payload) is (not payload["blocked"]), name

    @pytest.mark.parametrize("name", RUNS)
    def test_every_verdict_and_evidence_line_has_the_fields_a_component_reads(self, name):
        """Criterion 3 as a shape: field, value WITH its unit, provenance, and the gap reason
        when there is no value. Money is a STRING carrying its currency, never a number - a
        number would be a bare amount, and R9 is a USD reservation meeting its own ILS folio."""
        for verdict in golden(name)["verdicts"]:
            assert verdict["outcome"] in OUTCOMES
            assert verdict["record_id"] and verdict["means"] and "reason" in verdict
            for line in verdict["evidence"]:
                assert set(line) == {"field", "known", "value", "unit", "reason", "risk",
                                     "source"}
                if line["known"]:
                    assert isinstance(line["value"], str), (name, line)
                else:
                    assert line["value"] is None and line["reason"], (name, line)

    @pytest.mark.parametrize("name", RUNS)
    def test_the_counts_agree_with_the_verdicts_they_count(self, name):
        """What the parity harness on the React side relies on: one record, one bucket, and
        EXCLUDED its own - never folded into PASS."""
        payload = golden(name)
        if "counts" not in payload:
            return
        tally = {outcome: 0 for outcome in OUTCOMES}
        for verdict in payload["verdicts"]:
            tally[verdict["outcome"]] += 1
        assert {k: payload["counts"][k] for k in OUTCOMES} == tally
        assert payload["counts"]["total"] == len(payload["verdicts"])

    def test_criterion_3_the_overpaid_folio_is_traceable_with_its_currency(self):
        """Reservation 007004348 left with -490.75 ILS. The record, the field, the amount, the
        CURRENCY and the call that produced it are all in the payload, verbatim."""
        payload = golden("run/checkout_unrefunded_credit.sandbox.sandbox2026.json")
        (verdict,) = [v for v in payload["verdicts"] if v["record_id"] == "007004348"]
        assert verdict["outcome"] == "FAIL"
        (line,) = [l for l in verdict["evidence"] if l["field"] == "folio.balance_due"]
        assert line["value"] == "-490.75 ILS"
        assert line["unit"] == "ILS"
        assert line["source"].startswith("pms:")

    def test_criterion_10_the_index_names_what_to_connect(self):
        """`rate_room_category_consistency` is 3 of 5 on both providers, and the readiness says
        which two fields are missing - the sentence that turns UNKNOWN into a sales path."""
        controls = {c["control_id"]: c for c in golden("controls.json")["controls"]}
        assert sorted(controls) == list(available())
        readiness = controls["rate_room_category_consistency"]["readiness"]
        assert {r["provider"] for r in readiness} == set(provider_names())
        for report in readiness:
            assert (report["available"], report["total"]) == (3, 5)
            assert report["executable"] is False
            assert "rate_plan.permitted_room_types" in report["headline"]

    def test_history_rows_carry_the_same_two_gates(self):
        """A history chart is a run chart seen from further away: `concluded` beside counts,
        and no counts for a blocked run."""
        rows = golden("history/ooo_room_protection.json")["runs"]
        assert rows and all(row["concluded"] is False and "counts" in row for row in rows)
        rows = golden("history/resource_occupancy_consistency.json")["runs"]
        assert rows and all(row["blocked"] and "counts" not in row for row in rows)

    def test_the_drafts_golden_is_the_unwired_state(self):
        """Drafts are a reader's working state. The golden is the absence, stated."""
        assert golden("drafts.json") == {"wired": False, "drafts": []}
