/**
 * The golden payloads in fixtures/api/, generated by the engine (tools/dump_api_fixtures.py) and
 * never edited. This suite renders from them and nothing else: no engine process, no socket, and
 * no run is ever triggered - which is also why trap 4 cannot happen in a test.
 */
import { readdirSync, readFileSync } from "node:fs";
import { resolve } from "node:path";
import type { Outcomes, RunPayload } from "@/lib/types";

// `import.meta.dirname`, not `new URL(..., import.meta.url)`: under jsdom the latter is not a
// file URL, and the suite would fail before a single assertion.
export const GOLDEN = resolve(import.meta.dirname, "../../fixtures/api") + "/";

export const golden = <T,>(name: string): T => JSON.parse(readFileSync(GOLDEN + name, "utf-8")) as T;

export const outcomes = golden<Outcomes>("outcomes.json");

/** Every live run in the matrix: every control x property x capture. */
export const liveRuns = readdirSync(GOLDEN + "run").sort();

/** Every stored run - what the run page actually renders, since it reads runs back by id. */
export const storedRuns = readdirSync(GOLDEN + "runs").sort();

export const run = (name: string) => golden<RunPayload>("run/" + name);
export const stored = (name: string) => golden<RunPayload>("runs/" + name);
