/**
 * THE CONTRACT. The shapes of the hotelcontrols JSON API, as this UI reads them.
 *
 * Every field here is pinned on the Python side by tests/integration/test_api_goldens.py, and
 * every payload this UI's suite renders is a golden file in fixtures/api/, generated by the
 * engine and never edited. If one of these types and a golden payload disagree, the golden wins.
 *
 * Three fields are traps, and the types say so in their names and comments:
 *
 *   counts      present on a run that concluded NOTHING. The gate for the tile row is
 *               `coverage.concluded`, never the presence of `counts` (trap 1, finding F5).
 *   value       money is a string that CARRIES ITS CURRENCY: "-490.75 ILS". It is rendered
 *               verbatim and never parsed - a reservation in USD and its own folio in ILS share
 *               no exchange rate anywhere in the source system (R9).
 *   source      provenance: which system and which call produced a value. Opaque: displayed,
 *               never split, parsed or branched on. Branching on it would end the
 *               PMS-agnostic thesis in one `if`.
 */

export type OutcomeName = "PASS" | "FAIL" | "UNKNOWN" | "EXCLUDED";

export interface EvidenceLine {
  field: string;
  known: boolean;
  /** Verbatim, with its unit. Never parse. `null` exactly when `known` is false. */
  value: string | null;
  unit: string | null;
  /** Why the value is unknown. The commercial point of an UNKNOWN: what to connect. */
  reason: string | null;
  risk: string | null;
  /** Opaque provenance. Display only. */
  source: string | null;
}

export interface VerdictPayload {
  record_id: string | null;
  outcome: OutcomeName;
  means: string;
  reason: string;
  evidence: EvidenceLine[];
}

export interface ReadinessSource {
  name: string;
  available: number;
  total: number;
  missing: string[];
}

export interface ReadinessReport {
  provider: string;
  available: number;
  total: number;
  executable: boolean;
  headline: string;
  sources: ReadinessSource[];
  unresolvable: string[];
  tenant_supplied: string[];
}

export interface Counts {
  PASS: number;
  FAIL: number;
  UNKNOWN: number;
  EXCLUDED: number;
  total: number;
}

export interface Coverage {
  evaluated: number;
  total: number;
  /** THE gate for the tile row. */
  concluded: boolean;
  headline: string;
  reasons: { reason: string; records: number }[];
}

export interface RunPayload {
  control_id: string;
  control_name: string;
  natural_language: string;
  tenant_id: string;
  provider: string;
  evidence: { label: string; synthetic: boolean };
  as_of: string;
  created_at: string;
  calls: number;
  run_id: string;
  /** The reason the run could not happen, or null. A blocked run has no `counts` key at all. */
  blocked: string | null;
  coverage: Coverage;
  freshness: { stale: boolean; headline: string };
  /** Empty on a stored run: readiness is a fact about the spec, fetched separately. */
  readiness: ReadinessReport[];
  verdicts: VerdictPayload[];
  /** Present whenever the run was not blocked - INCLUDING when it concluded nothing. */
  counts?: Counts;
  execution?: { mode: string; declared_mode: string; fell_back: boolean; headline: string };
}

export interface OutcomeWording {
  outcome: OutcomeName;
  badge: string;
  means: string;
  group_meaning: string;
  open: boolean;
}

/** The four answers' words and the page's two orders, served by the engine (one source). */
export interface Outcomes {
  /** In tile order: what was concluded first, what was not after. */
  outcomes: OutcomeWording[];
  /** Work-queue order: what to act on first. */
  group_order: OutcomeName[];
}

export interface ControlEntry {
  control_id: string;
  name: string;
  natural_language: string;
  entity: string;
  reviewed: boolean;
  readiness: ReadinessReport[];
}

export interface Property {
  id: string;
  name: string;
  provider: string;
  captures: string[];
  default_capture: string;
}

export interface Properties {
  properties: Property[];
  default: { property: string; evidence: string };
}
