/**
 * THE CONTRACT. The shapes of the hotelcontrols JSON API, as this UI reads them.
 *
 * Every field here is pinned on the Python side by tests/integration/test_api_goldens.py, and
 * every payload this UI's suite renders is a golden file in fixtures/api/, generated by the
 * engine and never edited. If one of these types and a golden payload disagree, the golden wins.
 *
 * Three fields are traps, and the types say so in their names and comments:
 *
 *   counts      present on a run that concluded NOTHING. The gate for the tile row is
 *               `coverage.concluded`, never the presence of `counts` (trap 1, finding F5).
 *   value       money is a string that CARRIES ITS CURRENCY: "-490.75 ILS". It is rendered
 *               verbatim and never parsed - a reservation in USD and its own folio in ILS share
 *               no exchange rate anywhere in the source system (R9).
 *   source      provenance: which system and which call produced a value. Opaque: displayed,
 *               never split, parsed or branched on. Branching on it would end the
 *               PMS-agnostic thesis in one `if`.
 */

export type OutcomeName = "PASS" | "FAIL" | "UNKNOWN" | "EXCLUDED";

export interface EvidenceLine {
  field: string;
  known: boolean;
  /** Verbatim, with its unit. Never parse. `null` exactly when `known` is false. */
  value: string | null;
  unit: string | null;
  /** Why the value is unknown. The commercial point of an UNKNOWN: what to connect. */
  reason: string | null;
  risk: string | null;
  /** Opaque provenance. Display only. */
  source: string | null;
}

export interface VerdictPayload {
  record_id: string | null;
  outcome: OutcomeName;
  means: string;
  reason: string;
  evidence: EvidenceLine[];
}

export interface ReadinessSource {
  name: string;
  available: number;
  total: number;
  missing: string[];
}

export interface ReadinessReport {
  provider: string;
  available: number;
  total: number;
  executable: boolean;
  headline: string;
  sources: ReadinessSource[];
  unresolvable: string[];
  tenant_supplied: string[];
}

export interface Counts {
  PASS: number;
  FAIL: number;
  UNKNOWN: number;
  EXCLUDED: number;
  total: number;
}

export interface Coverage {
  evaluated: number;
  total: number;
  /** THE gate for the tile row. */
  concluded: boolean;
  headline: string;
  reasons: { reason: string; records: number }[];
}

export interface RunPayload {
  control_id: string;
  control_name: string;
  natural_language: string;
  tenant_id: string;
  provider: string;
  evidence: { label: string; synthetic: boolean };
  as_of: string;
  created_at: string;
  calls: number;
  run_id: string;
  /**
   * Which version of the rule judged this run, and the SHA-256 of what that version says
   * (slice 16). BOTH null on a run stored before rules carried a version: that is "version not
   * recorded", and it is never filled in with today's version.
   */
  policy_version: number | null;
  policy_digest: string | null;
  /** The reason the run could not happen, or null. A blocked run has no `counts` key at all. */
  blocked: string | null;
  coverage: Coverage;
  freshness: { stale: boolean; headline: string };
  /** Empty on a stored run: readiness is a fact about the spec, fetched separately. */
  readiness: ReadinessReport[];
  verdicts: VerdictPayload[];
  /** Present whenever the run was not blocked - INCLUDING when it concluded nothing. */
  counts?: Counts;
  execution?: { mode: string; declared_mode: string; fell_back: boolean; headline: string };
}

export interface OutcomeWording {
  outcome: OutcomeName;
  badge: string;
  means: string;
  group_meaning: string;
  open: boolean;
}

/** The four answers' words and the page's two orders, served by the engine (one source). */
export interface Outcomes {
  /** In tile order: what was concluded first, what was not after. */
  outcomes: OutcomeWording[];
  /** Work-queue order: what to act on first. */
  group_order: OutcomeName[];
}

export interface ControlEntry {
  control_id: string;
  name: string;
  natural_language: string;
  entity: string;
  reviewed: boolean;
  readiness: ReadinessReport[];
}

export interface Property {
  id: string;
  name: string;
  provider: string;
  captures: string[];
  default_capture: string;
}

export interface Properties {
  properties: Property[];
  default: { property: string; evidence: string };
}

/** One past run, as `/api/history/<control_id>` summarises it. Newest first, ties by run id. */
export interface HistoryRow {
  run_id: string;
  created_at: string;
  provider: string;
  evidence_label: string;
  as_of: string;
  calls: number;
  /** The rule that judged it, exactly as on a run. Both null: version not recorded. */
  policy_version: number | null;
  policy_digest: string | null;
  /** The reason the run could not happen, or null. A blocked row has no counts and no headline. */
  blocked: string | null;
  /** THE gate for the counts - exactly as on a run (trap 1). */
  concluded: boolean;
  /** The engine's sentence for where the counts would be. Null only for a blocked row. */
  headline: string | null;
  /** Present whenever the run was not blocked - INCLUDING when it concluded nothing. */
  counts?: Counts;
}

export interface History {
  control_id: string;
  /** Whose history this is (slice 17). The engine falls back to its default property when the
   * one asked for names nothing, and this says which it answered for. */
  property: string;
  runs: HistoryRow[];
}

/** One exchange of a compose conversation. */
export interface ComposeTurn {
  prose: string;
  sentence: string;
  question: string;
  /** Why it did not compile, in the validator's own words. Empty when it did. */
  problems: string[];
}

/** What compose can do here: whether a proposer is wired, and what a draft may borrow. */
export interface ComposeState {
  wired: boolean;
  proposer: string | null;
  drafts_wired: boolean;
  templates: { control_id: string; entity: string }[];
  template: string;
  conversation: string;
  transcript: ComposeTurn[];
}

/** The latest turn, in full. `ok` means the grammar parsed it AND the validator accepted it. */
export interface ComposeResult {
  prose: string;
  sentence: string;
  question: string;
  is_question: boolean;
  ok: boolean;
  problems: string[];
  fields: string[];
}

export interface ComposeTurnResponse {
  conversation: string;
  template: string;
  proposer: string;
  result: ComposeResult;
  transcript: ComposeTurn[];
}

/** A sentence sent back to be filed that the grammar refused. Nothing was written. */
export interface AcceptRefused {
  error: string;
  status: 422;
  sentence: string;
  problems: string[];
}

// ---------------------------------------------------------------- the findings queue (slice 18)
/** One task a VIOLATION raised, as `/api/actions` returns it. */
export interface ActionRecord {
  action_id: string;
  property: string;
  control_id: string;
  control_name: string;
  record_id: string;
  /** From the rule's own action block. `audience` is null when the rule names none. */
  severity: string;
  audience: string | null;
  type: string;
  /** The VIOLATION's own sentence. Money inside it carries its currency; never parse it. */
  reason: string;
  policy_version: number;
  policy_digest: string;
  state: "pending" | "done" | "dismissed";
  state_changed_at: string | null;
  state_changed_by: string | null;
  raised: { run_id: string; at: string; as_of: string; provider: string; evidence: string };
  last_failing: { run_id: string; at: string };
  /** A PASS since the newest failure, under the same rule. An annotation, never a state. */
  cleared: { run_id: string; at: string; as_of: string } | null;
  annotation: string | null;
  /**
   * Slice 19: what happened to the task's email. PRESENT ONLY when the engine has a notifier
   * wired (or the task carries a delivery fact from a session that had one). Absent is not
   * "not sent" - it is "email is not part of this engine's setup".
   */
  delivery?: { channel: string | null; sent_at: string | null; note: string | null };
}

/** What a control's latest run lets the queue say. Only "concluded" is a conclusion. */
export type QueueStatus = "concluded" | "no_conclusion" | "blocked" | "not_run";

export interface QueueControl {
  control_id: string;
  name: string;
  severity: string;
  audience: string | null;
  status: QueueStatus;
  /** The status in words, served by the engine so this UI never types its own copy. */
  label: string;
  /** The engine's sentence for this control's row. Rendered as it arrives. */
  headline: string;
  pending: number;
  /** Exactly a history row, or null when the control has not been run against this store. */
  latest_run: HistoryRow | null;
}

export interface Queue {
  property: string;
  /** False for the demo's default in-memory store - and then the queue is lost on restart. */
  persistent: boolean;
  persistence: string;
  pending: number;
  records: ActionRecord[];
  controls: QueueControl[];
  /** Slice 19: present only when a notifier is wired. Absent means nobody is emailed. */
  email?: { wired: boolean; via: string };
}
