# -*- coding: utf-8 -*-
"""
Slice 15's invariant: the React UI is an ADDITION, and the engine does not move.

The owner's stated priority for this slice is "nothing may break, no core logic may break", and
the brief turns that into one mechanical claim: no file the engine IS may change on a slice-15
branch. A Next.js UI is a second client of a JSON API that already exists. If building it ever
seems to need a change to the kernel, the evaluator or the store, the slice has been
misunderstood - and the honest cause is nearly always a field missing from the JSON, which is a
web-layer problem.

WHAT IS PROTECTED, AND WHY IT IS WIDER THAN THE BRIEF'S GREP
-------------------------------------------------------------
The brief's CI grep names the eight engine packages. This test protects all of `hotelcontrols/`
except `web/app.py` - the ONE file the slice is allowed to touch, to add read-only JSON routes.
`render.py`, `server.py` and the stylesheet are the existing surface, and the brief requires
that surface to keep working unmodified; a byte-level guard is the strongest form of that. It
also protects `spec/` (the IR files ARE the rules - editing one changes a verdict without
touching a line of Python) and the captured fixtures, which are evidence. The golden payloads
under `fixtures/api/` are the exception, because producing them is this slice's job.

WHEN IT RUNS
------------
Only on a `slice/15-*` branch. A permanent ban on engine changes would be absurd - the next
slice may well need one - so the guard is scoped to the slice whose promise it is. In CI the
branch comes from `GITHUB_HEAD_REF`, because a pull request is checked out as a detached merge
commit. When it runs and cannot find `origin/main` it FAILS rather than skips: a guard that
quietly stands down when its input is missing is not a guard.

It compares against the merge base INCLUDING the working tree and untracked files, so the
mistake is caught at the desk rather than at push.
"""
import os
import pathlib
import subprocess

import pytest

ROOT = pathlib.Path(__file__).resolve().parents[2]

# The one engine file slice 15 may change: new read-only GET routes, and nothing else.
PERMITTED = ("hotelcontrols/web/app.py",)

# What the engine is. A prefix match, so a new module inside any of these is covered too.
PROTECTED = ("hotelcontrols/", "spec/", "fixtures/")

# Generated by this slice (tools/dump_api_fixtures.py), so it is expected to change.
GENERATED = ("fixtures/api/",)

# A draft filed from the compose window during a local demo lands here untracked. It is a
# reader's working state, not a change to the engine, and it is never committed by this slice.
LOCAL_STATE = ("spec/drafts/ir/",)


def _git(*args: str) -> str:
    return subprocess.run(("git",) + args, cwd=ROOT, check=True, capture_output=True,
                          text=True).stdout


def _branch() -> str:
    return os.environ.get("GITHUB_HEAD_REF") or _git("rev-parse", "--abbrev-ref", "HEAD").strip()


def violations(paths, untracked=()) -> list[str]:
    """Every path a slice-15 change may not touch. Pure, so the rule itself can be tested."""
    found = []
    for path in sorted(set(paths) | set(untracked)):
        if path in PERMITTED or path.startswith(GENERATED):
            continue
        if path in untracked and path.startswith(LOCAL_STATE):
            continue
        if path.startswith(PROTECTED):
            found.append(path)
    return found


def _changed_since_main() -> tuple[list[str], list[str]]:
    try:
        base = _git("merge-base", "origin/main", "HEAD").strip()
    except (subprocess.CalledProcessError, FileNotFoundError) as exc:
        pytest.fail("slice-15 guard cannot find origin/main to compare against (%s). In CI the "
                    "checkout needs fetch-depth: 0." % exc)
    # Against the merge base and the WORKING TREE, not HEAD: an uncommitted edit to the kernel
    # is the same mistake as a committed one, caught earlier.
    changed = _git("diff", "--name-only", base).split()
    untracked = _git("ls-files", "--others", "--exclude-standard").split()
    return changed, untracked


@pytest.mark.skipif(not _branch().startswith("slice/15-"),
                    reason="the engine-untouched guard belongs to slice 15 branches only")
def test_no_engine_file_changed_on_a_slice_15_branch():
    """Brief §3: no file in the engine changes in this slice. Proven per PR, not promised."""
    changed, untracked = _changed_since_main()
    broken = violations(changed, untracked)
    assert not broken, ("SLICE 15 TOUCHED CORE LOGIC - STOP and ask the owner. Changed: %s"
                        % ", ".join(broken))


# ---------------------------------------------------------------------------------------
# The rule itself, tested on any branch, so the guard cannot rot into a test that always passes.
class TestTheGuardRule:

    @pytest.mark.parametrize("path", [
        "hotelcontrols/kernel/value.py", "hotelcontrols/evaluator/kleene.py",
        "hotelcontrols/store/sqlite.py", "hotelcontrols/runner/coverage.py",
        "hotelcontrols/compiler/grammar.py", "hotelcontrols/providers/minihotel/adapter.py",
        "hotelcontrols/evidence/budget.py", "hotelcontrols/spec/ir.py",
    ])
    def test_every_engine_package_is_protected(self, path):
        assert violations([path]) == [path]

    @pytest.mark.parametrize("path", [
        "hotelcontrols/web/render.py", "hotelcontrols/web/server.py",
        "hotelcontrols/web/assets/style.css",
    ])
    def test_the_existing_surface_is_protected_too(self, path):
        """Brief §11: the server-rendered surface still works, unmodified. Both UIs ship."""
        assert violations([path]) == [path]

    def test_a_rule_or_a_capture_is_protected_because_both_decide_verdicts(self):
        assert violations(["spec/ir/checkout_money_owed.json",
                           "fixtures/minihotel/index.json"]) == [
            "fixtures/minihotel/index.json", "spec/ir/checkout_money_owed.json"]

    def test_a_new_file_inside_an_engine_package_is_caught(self):
        assert violations([], untracked=["hotelcontrols/kernel/new.py"]) == [
            "hotelcontrols/kernel/new.py"]

    def test_the_routes_file_and_the_golden_payloads_are_permitted(self):
        assert violations(["hotelcontrols/web/app.py",
                           "fixtures/api/run/x.sandbox.sandbox2026.json"]) == []

    def test_the_ui_tools_tests_and_docs_are_outside_the_engine(self):
        assert violations(["ui/app/page.tsx", "tools/dump_api_fixtures.py",
                           "tests/unit/test_web_routing.py", "docs/prd.md"]) == []

    def test_a_draft_filed_during_a_demo_is_local_state_but_a_committed_one_is_not(self):
        draft = "spec/drafts/ir/my_rule.json"
        assert violations([], untracked=[draft]) == []
        assert violations([draft]) == [draft]
